theme = "tokyonight_storm"

[editor]
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
line-number = "relative"

[keys.insert.j]
k = "normal_mode"

[keys.select]
'$' = "goto_line_end"
0 = "goto_line_start"

[keys.normal]
'$' = "goto_line_end"
0 = "goto_line_start"


